# Generated by Django 5.0.1 on 2026-01-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_customuser_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='tariff_name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
